name: PlasmoEmotes
version: '${project.version}'
main: su.plo.emotes.Emotes
api-version: 1.18
softdepend:
  - ProtocolLib
authors: [ Apehum ]
commands:
  emotes:
    permission: emotes.list

permissions:
  emotes.list:
    default: true
